#include "matrix.h"
const int MATRIX_LEN = 7;

const struct Opcode MATRIX[] = {
    {.N="hlt", .M={{.V=true ,.X="0000"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},}},
    {.N="int", .M={{.V=true ,.X="0001"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},}},
    {.N="rti", .M={{.V=true ,.X="0002"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},}},
    {.N="mov", .M={{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=true ,.X="0006"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=true ,.X="004R"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=true ,.X="0007"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=true ,.X="005R"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=true ,.X="001R"},{.V=true ,.X="002R"},{.V=true ,.X="003R"},{.V=true ,.X="01XY"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},}},
    {.N="phf", .M={{.V=true ,.X="000D"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},}},
    {.N="ppf", .M={{.V=true ,.X="000E"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},}},
    {.N="nop", .M={{.V=true ,.X="000F"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},{.V=false,.X="----"},}},
};
